# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(493, 674)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 180, 321, 16))
        self.label.setObjectName("label")
        self.frameEpochs = QtWidgets.QFrame(Dialog)
        self.frameEpochs.setEnabled(False)
        self.frameEpochs.setGeometry(QtCore.QRect(10, 200, 471, 91))
        self.frameEpochs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEpochs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEpochs.setObjectName("frameEpochs")
        self.ButtonGetEpochs = QtWidgets.QPushButton(self.frameEpochs)
        self.ButtonGetEpochs.setGeometry(QtCore.QRect(30, 10, 211, 23))
        self.ButtonGetEpochs.setObjectName("ButtonGetEpochs")
        self.ButtonPlotEpochs = QtWidgets.QPushButton(self.frameEpochs)
        self.ButtonPlotEpochs.setGeometry(QtCore.QRect(290, 10, 141, 21))
        self.ButtonPlotEpochs.setObjectName("ButtonPlotEpochs")
        self.ButtonPlotEpochsAverage = QtWidgets.QPushButton(self.frameEpochs)
        self.ButtonPlotEpochsAverage.setGeometry(QtCore.QRect(290, 60, 141, 23))
        self.ButtonPlotEpochsAverage.setObjectName("ButtonPlotEpochsAverage")
        self.label_11 = QtWidgets.QLabel(self.frameEpochs)
        self.label_11.setGeometry(QtCore.QRect(160, 40, 59, 15))
        self.label_11.setObjectName("label_11")
        self.doubleSpinBoxTmax = QtWidgets.QDoubleSpinBox(self.frameEpochs)
        self.doubleSpinBoxTmax.setGeometry(QtCore.QRect(160, 60, 66, 24))
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMinimum(-2.0)
        self.doubleSpinBoxTmax.setMaximum(4.0)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 4.0)
        self.doubleSpinBoxTmax.setObjectName("doubleSpinBoxTmax")
        self.label_12 = QtWidgets.QLabel(self.frameEpochs)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 59, 15))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBoxTmin = QtWidgets.QDoubleSpinBox(self.frameEpochs)
        self.doubleSpinBoxTmin.setGeometry(QtCore.QRect(30, 60, 66, 24))
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-2.0)
        self.doubleSpinBoxTmin.setMaximum(4.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setProperty("value", -2.0)
        self.doubleSpinBoxTmin.setObjectName("doubleSpinBoxTmin")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 50, 321, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ButtonPlotRawData = QtWidgets.QPushButton(self.frame_2)
        self.ButtonPlotRawData.setEnabled(False)
        self.ButtonPlotRawData.setGeometry(QtCore.QRect(180, 20, 131, 23))
        self.ButtonPlotRawData.setObjectName("ButtonPlotRawData")
        self.ButtonLoadData = QtWidgets.QPushButton(self.frame_2)
        self.ButtonLoadData.setGeometry(QtCore.QRect(30, 40, 101, 23))
        self.ButtonLoadData.setObjectName("ButtonLoadData")
        self.ButtonFilterRawData = QtWidgets.QPushButton(self.frame_2)
        self.ButtonFilterRawData.setEnabled(False)
        self.ButtonFilterRawData.setGeometry(QtCore.QRect(180, 60, 131, 23))
        self.ButtonFilterRawData.setObjectName("ButtonFilterRawData")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 101, 16))
        self.label_2.setObjectName("label_2")
        self.framePlottingEvoked = QtWidgets.QFrame(Dialog)
        self.framePlottingEvoked.setEnabled(False)
        self.framePlottingEvoked.setGeometry(QtCore.QRect(10, 300, 471, 361))
        self.framePlottingEvoked.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlottingEvoked.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlottingEvoked.setObjectName("framePlottingEvoked")
        self.ButtonPlotSingleTopomap = QtWidgets.QPushButton(self.framePlottingEvoked)
        self.ButtonPlotSingleTopomap.setGeometry(QtCore.QRect(160, 20, 191, 25))
        self.ButtonPlotSingleTopomap.setObjectName("ButtonPlotSingleTopomap")
        self.SliderSingleTopomap = QtWidgets.QSlider(self.framePlottingEvoked)
        self.SliderSingleTopomap.setGeometry(QtCore.QRect(120, 60, 281, 16))
        self.SliderSingleTopomap.setOrientation(QtCore.Qt.Horizontal)
        self.SliderSingleTopomap.setObjectName("SliderSingleTopomap")
        self.SliderFinalTopomap = QtWidgets.QSlider(self.framePlottingEvoked)
        self.SliderFinalTopomap.setGeometry(QtCore.QRect(120, 160, 281, 16))
        self.SliderFinalTopomap.setMaximum(99)
        self.SliderFinalTopomap.setProperty("value", 0)
        self.SliderFinalTopomap.setOrientation(QtCore.Qt.Horizontal)
        self.SliderFinalTopomap.setObjectName("SliderFinalTopomap")
        self.SliderInitialTopomap = QtWidgets.QSlider(self.framePlottingEvoked)
        self.SliderInitialTopomap.setGeometry(QtCore.QRect(120, 130, 281, 16))
        self.SliderInitialTopomap.setOrientation(QtCore.Qt.Horizontal)
        self.SliderInitialTopomap.setObjectName("SliderInitialTopomap")
        self.ButtonPlotTopomapBetweenEvoked = QtWidgets.QPushButton(self.framePlottingEvoked)
        self.ButtonPlotTopomapBetweenEvoked.setGeometry(QtCore.QRect(160, 100, 191, 23))
        self.ButtonPlotTopomapBetweenEvoked.setObjectName("ButtonPlotTopomapBetweenEvoked")
        self.label_3 = QtWidgets.QLabel(self.framePlottingEvoked)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.framePlottingEvoked)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.framePlottingEvoked)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_5.setObjectName("label_5")
        self.spinBoxInitialTopomap = QtWidgets.QSpinBox(self.framePlottingEvoked)
        self.spinBoxInitialTopomap.setGeometry(QtCore.QRect(410, 120, 47, 24))
        self.spinBoxInitialTopomap.setObjectName("spinBoxInitialTopomap")
        self.spinBoxSingleTopomap = QtWidgets.QSpinBox(self.framePlottingEvoked)
        self.spinBoxSingleTopomap.setGeometry(QtCore.QRect(410, 50, 47, 24))
        self.spinBoxSingleTopomap.setObjectName("spinBoxSingleTopomap")
        self.spinBoxFinalTopomap = QtWidgets.QSpinBox(self.framePlottingEvoked)
        self.spinBoxFinalTopomap.setGeometry(QtCore.QRect(410, 150, 47, 24))
        self.spinBoxFinalTopomap.setObjectName("spinBoxFinalTopomap")
        self.frame_4 = QtWidgets.QFrame(self.framePlottingEvoked)
        self.frame_4.setGeometry(QtCore.QRect(20, 220, 431, 131))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_9.setObjectName("label_9")
        self.SpinBoxInitialTimeTopomap = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.SpinBoxInitialTimeTopomap.setGeometry(QtCore.QRect(90, 10, 66, 31))
        self.SpinBoxInitialTimeTopomap.setDecimals(3)
        self.SpinBoxInitialTimeTopomap.setMinimum(-2.0)
        self.SpinBoxInitialTimeTopomap.setMaximum(4.0)
        self.SpinBoxInitialTimeTopomap.setSingleStep(0.01)
        self.SpinBoxInitialTimeTopomap.setProperty("value", -0.5)
        self.SpinBoxInitialTimeTopomap.setObjectName("SpinBoxInitialTimeTopomap")
        self.SpinBoxFinalTimeTopomap = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.SpinBoxFinalTimeTopomap.setGeometry(QtCore.QRect(90, 50, 66, 31))
        self.SpinBoxFinalTimeTopomap.setDecimals(3)
        self.SpinBoxFinalTimeTopomap.setMinimum(-2.0)
        self.SpinBoxFinalTimeTopomap.setMaximum(4.0)
        self.SpinBoxFinalTimeTopomap.setSingleStep(0.01)
        self.SpinBoxFinalTimeTopomap.setProperty("value", 1.0)
        self.SpinBoxFinalTimeTopomap.setObjectName("SpinBoxFinalTimeTopomap")
        self.SpinBoxIntervalTopomap = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.SpinBoxIntervalTopomap.setGeometry(QtCore.QRect(90, 90, 66, 31))
        self.SpinBoxIntervalTopomap.setDecimals(3)
        self.SpinBoxIntervalTopomap.setMaximum(1.0)
        self.SpinBoxIntervalTopomap.setSingleStep(0.005)
        self.SpinBoxIntervalTopomap.setProperty("value", 0.3)
        self.SpinBoxIntervalTopomap.setObjectName("SpinBoxIntervalTopomap")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(165, 20, 67, 15))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(165, 60, 67, 15))
        self.label_14.setObjectName("label_14")
        self.doubleSpinBoxVmax = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxVmax.setGeometry(QtCore.QRect(234, 10, 66, 31))
        self.doubleSpinBoxVmax.setDecimals(1)
        self.doubleSpinBoxVmax.setMinimum(-100.0)
        self.doubleSpinBoxVmax.setSingleStep(10.0)
        self.doubleSpinBoxVmax.setProperty("value", 80.0)
        self.doubleSpinBoxVmax.setObjectName("doubleSpinBoxVmax")
        self.doubleSpinBoxVmin = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxVmin.setGeometry(QtCore.QRect(234, 50, 66, 31))
        self.doubleSpinBoxVmin.setDecimals(1)
        self.doubleSpinBoxVmin.setMinimum(-100.0)
        self.doubleSpinBoxVmin.setSingleStep(10.0)
        self.doubleSpinBoxVmin.setProperty("value", -80.0)
        self.doubleSpinBoxVmin.setObjectName("doubleSpinBoxVmin")
        self.radioButtonChNames = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonChNames.setGeometry(QtCore.QRect(165, 90, 131, 31))
        self.radioButtonChNames.setAutoExclusive(False)
        self.radioButtonChNames.setObjectName("radioButtonChNames")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(311, 17, 31, 20))
        self.label_10.setObjectName("label_10")
        self.spinBoxTopoSize = QtWidgets.QSpinBox(self.frame_4)
        self.spinBoxTopoSize.setGeometry(QtCore.QRect(370, 10, 48, 31))
        self.spinBoxTopoSize.setMinimum(1)
        self.spinBoxTopoSize.setMaximum(10)
        self.spinBoxTopoSize.setProperty("value", 2)
        self.spinBoxTopoSize.setObjectName("spinBoxTopoSize")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(311, 60, 59, 15))
        self.label_15.setObjectName("label_15")
        self.spinBoxContours = QtWidgets.QSpinBox(self.frame_4)
        self.spinBoxContours.setGeometry(QtCore.QRect(370, 50, 47, 30))
        self.spinBoxContours.setMaximum(20)
        self.spinBoxContours.setProperty("value", 6)
        self.spinBoxContours.setObjectName("spinBoxContours")
        self.radioButtonBoundary = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonBoundary.setGeometry(QtCore.QRect(310, 95, 121, 21))
        self.radioButtonBoundary.setChecked(True)
        self.radioButtonBoundary.setAutoExclusive(False)
        self.radioButtonBoundary.setObjectName("radioButtonBoundary")
        self.label_6 = QtWidgets.QLabel(self.framePlottingEvoked)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 131, 16))
        self.label_6.setObjectName("label_6")
        self.ButtonClearFigures = QtWidgets.QPushButton(Dialog)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(360, 50, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 56, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 56, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 56, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.Button2PDF = QtWidgets.QPushButton(Dialog)
        self.Button2PDF.setGeometry(QtCore.QRect(360, 135, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.Button2PNG = QtWidgets.QPushButton(Dialog)
        self.Button2PNG.setGeometry(QtCore.QRect(421, 136, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(368, 113, 89, 16))
        self.label_16.setObjectName("label_16")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(349, 130, 121, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.framePlottingEvoked.raise_()
        self.frame_2.raise_()
        self.label.raise_()
        self.frameEpochs.raise_()
        self.label_2.raise_()
        self.ButtonClearFigures.raise_()
        self.Button2PDF.raise_()
        self.Button2PNG.raise_()
        self.label_16.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ephys"))
        self.label.setText(_translate("Dialog", "Epochs"))
        self.ButtonGetEpochs.setText(_translate("Dialog", "Get Epochs from Excel file"))
        self.ButtonPlotEpochs.setText(_translate("Dialog", "Plot Epochs"))
        self.ButtonPlotEpochsAverage.setText(_translate("Dialog", "Plot Epochs Average"))
        self.label_11.setText(_translate("Dialog", "tmax(s)"))
        self.label_12.setText(_translate("Dialog", "tmin(s)"))
        self.ButtonPlotRawData.setText(_translate("Dialog", "Plot Raw Data"))
        self.ButtonLoadData.setText(_translate("Dialog", "Load Raw Data"))
        self.ButtonFilterRawData.setText(_translate("Dialog", "Filter Raw Data"))
        self.label_2.setText(_translate("Dialog", "Raw Data"))
        self.ButtonPlotSingleTopomap.setText(_translate("Dialog", "Plot Single Topomap"))
        self.ButtonPlotTopomapBetweenEvoked.setText(_translate("Dialog", "Plot Topomap between Evoked"))
        self.label_3.setText(_translate("Dialog", "Evoked number"))
        self.label_4.setText(_translate("Dialog", "Initial Evoked"))
        self.label_5.setText(_translate("Dialog", "Final Evoked"))
        self.label_7.setText(_translate("Dialog", "Initial time"))
        self.label_8.setText(_translate("Dialog", "Final time"))
        self.label_9.setText(_translate("Dialog", "Interval"))
        self.label_13.setText(_translate("Dialog", "Vmax(mV)"))
        self.label_14.setText(_translate("Dialog", "Vmin(mV)"))
        self.radioButtonChNames.setText(_translate("Dialog", "Show Ch names"))
        self.label_10.setText(_translate("Dialog", "Size"))
        self.label_15.setText(_translate("Dialog", "Contours"))
        self.radioButtonBoundary.setText(_translate("Dialog", "Show Outlines"))
        self.label_6.setText(_translate("Dialog", "Plotting features"))
        self.ButtonClearFigures.setText(_translate("Dialog", "Close Figures"))
        self.Button2PDF.setText(_translate("Dialog", "PDF"))
        self.Button2PNG.setText(_translate("Dialog", "PNG"))
        self.label_16.setText(_translate("Dialog", "Export Figures"))

